export default {
  TOGGLE_CART_DROPDOWN: "TOGGLE_CART_DROPDOWN",
  ADD_CART_ITEM: "ADD_CART_ITEM",
  REMOVE_CART_ITEM: "REMOVE_CART_ITEM",
  INCREMENT_CART_ITEM_QUANTITY: "INCREMENT_CART_ITEM_QUANTITY", 
  DECREMENT_CART_ITEM_QUANTITY: "DECREMENT_CART_ITEM_QUANTITY" 
}